# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Geomsf_by_psu_packageBuilder
                                 A QGIS plugin
 Automates the preparation of QField survey packages from the 2023 Geo-enabled Master Sample Frame (GeoMSF).
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-03-29
        copyright            : (C) 2026 by Jomari M. Daison
        email                : jomari.daison@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Geomsf_by_psu_packageBuilder class from file Geomsf_by_psu_packageBuilder.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Geomsf_by_psu_packageBuilder import Geomsf_by_psu_packageBuilder
    return Geomsf_by_psu_packageBuilder(iface)
